name: publish chromium versions
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 1 * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          npx --version > report.txt
          date >> report.txt
      - name: Commit report
        run: |
          git config --global user.name 'automation'
          git config --global user.email 'automation@noreply.github.com'
          git add report.txt
          git commit -m "updated automated report"
          git push
